---
version: '3.7'
services:
  alarm-server:
    image: lnlscon/alarm-server:v1.1
    networks:
      - host
    #volumes:
    #  - "/var/tmp/zoo:/opt/data/zookeeper:rw"
    #  - "/var/tmp/kafka:/opt/data/kafka-logs:rw"
    environment:
      ZOO_PORT: 2181
      KAFKA_PORT: 29094
  
  alarm-logger:
    image: lnlscon/alarm-logger:v1.1
    networks:
      - host
    environment:
      ES_PORT: 9202
      KAFKA_PORT: 29094

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.2
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - discovery.type=single-node
    ports:
      - 9202:9200
    networks:
      - alarm-net

  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.4
    ports:
        - "5602:5601"
    environment:
      SERVER_NAME: epics.logging.kibana
      ELASTICSEARCH_HOSTS: http://es:9200
    networks:
      - alarm-net

  zookeeper:
    image: "confluentinc/cp-zookeeper:5.2.1"
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - alarm-net

  kafka0:
    image: "confluentinc/cp-enterprise-kafka:5.2.1"
    ports:
      - '9092:9092'
      - '29094:29094'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: LISTENER_INTERNAL://kafka0:29092,LISTENER_HOST://kafka0:9092,LISTENER_EXTERNAL://kafka0:29094
      KAFKA_ADVERTISED_LISTENERS: LISTENER_INTERNAL://kafka0:29092,LISTENER_HOST://localhost:9092,LISTENER_EXTERNAL://CA-RaCtrl-CO-Srv-1:29094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INTERNAL:PLAINTEXT,LISTENER_HOST:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INTERNAL
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100
    networks:
      - alarm-net

  kafkacat:
    image: confluentinc/cp-kafkacat
    command: sleep infinity
    networks:
      - alarm-net

networks:
  host:
    external:
      name: "host"
  alarm-net:

